# Generated by Django 3.1 on 2022-08-23 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=100)),
                ('team2', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ready-to-start', 'Ready to Start'), ('ongoing', 'Ongoing'), ('end', 'End')], max_length=100)),
                ('point1', models.CharField(blank=True, max_length=10, null=True)),
                ('point2', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.TimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'db_table': 'games',
            },
        ),
    ]
