# Generated by Django 3.1 on 2022-08-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220823_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='duration',
        ),
        migrations.AddField(
            model_name='game',
            name='startTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
