# Generated by Django 3.1 on 2022-08-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220823_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='liveLink',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
