# Generated by Django 3.0.8 on 2022-09-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/%y'),
        ),
        migrations.AddField(
            model_name='game',
            name='videoTitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
